# Build Stage
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests && \
    rm -rf ~/.m2/repository /app/ui/target/test-classes /app/api/target/test-classes

# Runtime Stage
FROM openjdk:17.0.1-jdk-slim
WORKDIR /app
COPY --from=build /app/ui/target/mnemonics-ui.jar /
EXPOSE 8080:8080
ENTRYPOINT ["java", "-jar", "/mnemonics-ui.jar"]